//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mensagems
    {
        public int Id { get; set; }
        public string UserOrigem { get; set; }
        public string UserDestimo { get; set; }
        public System.DateTime Data { get; set; }
        public string Titulo { get; set; }
        public string Corpo { get; set; }
        public int Flag { get; set; }
    }
}
